.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH VIM-RAILS-SETUP 1 "August 18, 2007" "rails-toolkit" "User Commands"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
vim-rails-setup \- Activate the vim-rails vim addon suite
.SH SYNOPSIS
.B vim-rails-setup
.I [\-\-remove]
.LP
.SH DESCRIPTION
vim-rails-setup installs the vim-rails addon suite making it available
from within vim. By default it will only affect the current user. However
if you run the program as superuser then the addon will be made available
system wide.
.PP
.SH OPTIONS
.TP
.B \-\-remove
Removes the addon from within vim. Again if run as superuser the addon
is removed system wide.
.SH SEE ALSO
.PP
vim (1), vim-addons (1).
.br
.SH NOTES
See the HTML documentation for a full description of the scripts in the
package -
.RI /usr/share/doc/vim-rails/html/index.html
.SH AUTHOR
vim-rails is a collection of vim-scripts assembled and glued together by Neil Wilson <aldursys@gmail.com>.
.PP
This manual page was written by Neil Wilson <aldursys@gmail.com>,
for the Debian project (but may be used by others).
